---
name: Build and Publish for Main and Release branches

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - releases/**
  workflow_dispatch:

jobs:
  audit-containers:
    name: Audit - Containers
    uses: DFE-Digital/funding-service-workflows/.github/workflows/audit-container-trivy.yml@7f8be92be250dc19cc1e67e6eee0c84a87ccedb9
    with:
      dockerfilePath: Pds.Admin.Api/Dockerfile
    secrets:
      buildArgs: ${{ secrets.DOCKER_BUILD_ARG }}
  lint-yaml:
    name: Lint - YAML
    uses: DFE-Digital/funding-service-workflows/.github/workflows/lint-yaml.yml@7f8be92be250dc19cc1e67e6eee0c84a87ccedb9
  build:
    name: Build and Publish
    uses: DFE-Digital/funding-service-workflows/.github/workflows/build-and-publish.yml@7f8be92be250dc19cc1e67e6eee0c84a87ccedb9
    needs: [audit-containers, lint-yaml]
    secrets: inherit
